package com.s95ammar.budgetplanner.ui.common

object Keys {
    const val KEY_PERIODIC_CATEGORY = "KEY_PERIODIC_CATEGORY"
    const val KEY_PERIODIC_CATEGORY_REQUEST = "KEY_PERIODIC_CATEGORY_REQUEST"
    const val KEY_LOCATION = "KEY_LOCATION"
    const val KEY_LOCATION_REQUEST = "KEY_LOCATION_REQUEST"
    const val KEY_ESTIMATE = "KEY_ESTIMATE"
    const val KEY_ESTIMATE_REQUEST = "KEY_ESTIMATE_REQUEST"

    const val KEY_NAME = "KEY_NAME"
    const val KEY_DRAWABLE_RES = "KEY_DRAWABLE_RES"

}