package com.s95ammar.budgetplanner.ui.common

object Keys {
    const val KEY_BUDGET_ID = "KEY_BUDGET_ID"
    const val KEY_BUDGET_TITLE = "KEY_BUDGET_TITLE"
    const val KEY_BUDGET_IS_ACTIVE = "KEY_BUDGET_IS_ACTIVE"
    const val KEY_ACTIVE_BUDGET_ID = "KEY_ACTIVE_BUDGET_ID"
    const val KEY_AUTH_TOKEN = "KEY_AUTH_TOKEN"
    const val KEY_RESULT_ACTIVE_BUDGET_CHANGED = "KEY_RESULT_ACTIVE_BUDGET_CHANGED"

    const val KEY_CATEGORY_ID = "KEY_CATEGORY_ID"
    const val KEY_CATEGORY = "KEY_CATEGORY"
    const val KEY_PERIODIC_CATEGORY = "KEY_PERIODIC_CATEGORY"
    const val KEY_ON_CATEGORY_CREATE_EDIT = "KEY_ON_CATEGORY_CREATE_EDIT"
    const val KEY_ON_PERIOD_CREATE_EDIT = "KEY_ON_PERIOD_CREATE_EDIT"
    // TODO: rename
    const val KEY_PERIODIC_CATEGORIES_SCREEN_ON_PERIODS_LIST_CHANGED = "KEY_PERIODIC_CATEGORIES_SCREEN_ON_PERIODS_LIST_CHANGED"
    const val KEY_ON_CATEGORY_SELECTED = "KEY_ON_CATEGORY_SELECTED"
    const val KEY_ON_PERIODIC_CATEGORY_SELECTED = "KEY_ON_PERIODIC_CATEGORY_SELECTED"

    const val KEY_NAME = "KEY_NAME"
    const val KEY_DRAWABLE_RES = "KEY_DRAWABLE_RES"

}