package com.s95ammar.budgetplanner.ui.common

object Keys {
    const val KEY_CATEGORY_OF_PERIOD = "KEY_CATEGORY_OF_PERIOD"
    const val KEY_CATEGORY_OF_PERIOD_REQUEST = "KEY_CATEGORY_OF_PERIOD_REQUEST"
    const val KEY_LOCATION = "KEY_LOCATION"
    const val KEY_LOCATION_REQUEST = "KEY_LOCATION_REQUEST"
    const val KEY_ESTIMATE = "KEY_ESTIMATE"
    const val KEY_ESTIMATE_REQUEST = "KEY_ESTIMATE_REQUEST"
    const val KEY_CURRENCY = "KEY_CURRENCY"
    const val KEY_CURRENCY_REQUEST = "KEY_CURRENCY_REQUEST"
    const val KEY_AMOUNT = "KEY_AMOUNT"
    const val KEY_AMOUNT_REQUEST = "KEY_AMOUNT_REQUEST"

    const val KEY_NAME = "KEY_NAME"
    const val KEY_DRAWABLE_RES = "KEY_DRAWABLE_RES"

}